name: dart_quill_delta_simplify 
description: "A Dart package designed to streamline the manipulation of Quill Delta, making complex operations straightforward"
version: 10.8.5
homepage: https://github.com/FlutterQuill/dart-quill-delta-simplify
documentation: https://github.com/FlutterQuill/dart-quill-delta-simplify/tree/master/documentation
issue_tracker: https://github.com/FlutterQuill/dart-quill-delta-simplify/issues

topics: 
  - flutter-quill 
  - quill-delta
  - delta 
  - quill

environment:
  sdk: ^3.0.0

dependencies:

  dart_quill_delta: ^10.8.3 
  flutter_quill: ^10.8.5
  meta: ^1.15.0
  collection: ^1.18.0
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.25.14
  lints: ^4.0.0

flutter:
  uses-material-design: true
