name: Feature request 
description: A new feature for Dart Quill Delta Simplication.
labels: 'enhancement'
body:
  - type: textarea 
    attributes:
      label: Describe the feature 
      description: A clear and concise description of what is your suggestion.
    validations:
      required: true
